### PR TITLE
OPENNLP-393: add contributors wanted issues list

### PR DESCRIPTION
**Pull request by kinow**
As per OPENNLP-393 comments, updating the Get Involved page with the list of contributions wanted issues.

Screen shot of what it will look like:

contributions-wanted-preview-1-fullpage

### CODE REVIEW

**Comment by wcolen** [comment]
Do you think we can automate this a little? Maybe we add a tag to the issues we want here and get it using RSS feed.

https://github.com/sdepold/jquery-rss
feed:https://issues.apache.org/jira/sr/jira.issueviews:searchrequest-rss/temp/SearchRequest.xml?jqlQuery=project+%3D+OPENNLP+AND+resolution+%3D+Unresolved+ORDER+BY+priority+DESC&tempMax=1000

**Comment by kinow** [comment]
I suggested something like that, but @kottmann raised a good point that JIRA is not that reliable, and could cause issues in the web site. Also, we would stress a bit more on our JIRA server. Now, having a job somewhere in INFRA running every night, and then updating a section of the site... that would be an interesting new small utility, but I think the INFRA team would like to implement it.

**Comment by wcolen** [comment]
Good point
+1 lgtm

**Comment by kinow** [comment]
Merged.

**Pull request merged**
