### PR TITLE
Update team.ad page

### PR DESCRIPTION
**Pull request by mawiesne**
Updates team page with a new C-level member (`this`).

### CODE REVIEW

**Review by kinow — APPROVED** [review]

**Comment by jzonthemtn** [comment]
+1 @mawiesne See if you can merge this ok!

**Comment by jzonthemtn** [comment]
@mawiesne As a committer you should have the merge button on this and the opennlp repository. Let me see where I need to get you added for that to work.

**Comment by rzo1** [comment]
> @mawiesne As a committer you should have the merge button on this and the opennlp repository. Let me see where I need to get you added for that to work.

LDAP groups looks correct. Looks like the account isn't part of the ORG in GitHub yet. Perhaps, it isn't 2FA enabled and sync linked with Gitbox. This can be done via self service at https://gitbox.apache.org/ - if the linking is done, the boxer app should add the account to the committer group + ORG on GitHub automatically.

**Comment by mawiesne** [comment]
My GH account is 2FA since ~10 mins and I updated my GH account name via _whimsy_. 🧐

EDIT: ASF Boxer in progress now...

**Comment by jzonthemtn** [comment]
Nice!

**Pull request merged**
