### PR TITLE
OPENNLP-1103 add AirNZ case

### PR DESCRIPTION
**Pull request by kinow**
First case from AirNZ. See ticket for more background on where it came from. The following screen shot displays what the website looks like after applying this change.

screenshot_2017-06-30_11-21-48

### CODE REVIEW

**Comment by smarthi** [comment]
+1 lgtm

**Review by smarthi — APPROVED** [review]
+1 lgtm

**Comment by kojisekig** [comment]
+1 lgtm

**Review by kottmann — APPROVED** [review]
+1 lgtm

**Pull request closed without merging**
