### PR TITLE
OPENNLP-1104 fix poweredby images, and use lower case in url's

### PR DESCRIPTION
**Pull request by kinow**
Fixes the images at the bottom of the page, and uses lower case to match what other pages look like.

### CODE REVIEW

**Comment by kinow** [comment]
before

**Comment by kinow** [comment]
after

**Review by smarthi — APPROVED** [review]
+1 lgtm

**Comment by danielruss** [comment]
Have you considered using the same color gradient for the "Powered by" text?

**Comment by kinow** [comment]
Oh, sounds like a good idea @danielruss ! Will give it a try and send an example on the slack channel this weekend

**Pull request closed without merging**
