### PR TITLE
Add Google Analytics

### PR DESCRIPTION
**Pull request by kottmann**

### CODE REVIEW

**Review by smarthi — APPROVED** [review]

**Review by kinow — COMMENTED** [review]
JS files may slow down loading the rest of the site. Hence they are normally put in the footer.

We have some JS in the footer already, so I think the GA ones could go there as well?

https://github.com/apache/opennlp-site/blob/master/src/main/jbake/templates/footer.ftl

**Comment by rzo1** [comment]
The use of Google analytics isn't encouraged at ASF anymore. Do we want to switch to the ASF Matomo instance?

**Comment by jzonthemtn** [comment]
> The use of Google analytics isn't encouraged at ASF anymore. Do we want to switch to the ASF Matomo instance?

I'm ok with that. It would be neat to be able to see how many visitors come to the site and what pages are most important.

**Comment by rzo1** [comment]
I can prepare the PR + request the site id. Have done that for TomEE, so should be a quick win.

**Comment by jzonthemtn** [comment]
I'm going to close this PR in favor of #73.

**Pull request closed without merging**
