### PR TITLE
Adds News page.

### PR DESCRIPTION
**Pull request by jzonthemtn**
screenshot from 2017-05-08 19-18-11

### CODE REVIEW

**Comment by kinow** [comment]
+1! Tested locally, and worked fine. Thought it was missing the template file, but it was actually the index under the news folder. Nice catch.

**Comment by kinow** [comment]
@jzonthemtn this has been merged, but the ASF bot - for some reason - is not closing pull requests merged (even with the "This closes #1234" commit message). Could you close it, please?

**Comment by smarthi** [comment]
Let's update this list to include 1.8.0 release while merging.  +1 to merge.

**Review by smarthi — APPROVED** [review]

**Comment by kinow** [comment]
@smarthi this has been merged already, but we need either @jzonthemtn to close the pull request, or wait till someone makes master the default branch in this repository. Then we can close it via an empty commit.

**Pull request closed without merging**
